name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew clean buildPlugin
      - name: Upload MiraiQQBOT artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MiraiQQBOT
          path: build/mirai/MiraiQQBOT-*.jar